name: Publish to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Todo use our .nvmrc instead
      - name: Install dependencies and build 🔧
        run: npm ci && npm run release
      - name: Publish package on NPM 📦
        run: npm run publish:npm
        env:
          NPM_CONFIG_PROVENANCE: 'true'
          NPM_CONFIG_LOGLEVEL: 'verbose'
